name: Karate API Tests (Gradle)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Karate Tests
        run: ./gradlew clean test
